---
- name: Deploy XYZtechnologies WAR App to Docker
  hosts: localhost
  vars:
    app_name: xyztech
    image_name: "{{ app_name }}-app"
    container_name: "{{ app_name }}-container"
    host_port: 8282
    container_port: 8080

  tasks:
    - name: Build Docker image from current directory
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: latest
        build:
          path: "{{ playbook_dir }}"
        source: build
        force_source: true  # forces rebuild

    - name: Remove existing container if exists
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: true

    - name: Run Docker container from built image
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "{{ host_port }}:{{ container_port }}"
