apiVersion: v1
kind: Service
metadata:
  name: xyztech-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: yxztech
  ports:
    - port: 80           # Port to expose the service on (inside the cluster)
      targetPort: 8080   # The port your Tomcat container listens on
      nodePort: 30080    # Exposes service on <NodeIP>:30080 externally
